language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

os:
    - linux


python:
    - 3.5

env:
    global:
        # SET DEFAULTS TO AVOID REPEATING IN MOST CASES
        - SETUPTOOLS_VERSION=stable
        - PIP_INSTALL='pip install'
        - INSTALL_OPTIONAL=true
        - SETUP_CMD='test'

before_install:

    # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST
    # FUTURE CHANGES
    - export PYTHONIOENCODING=UTF8

    # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    #CHECK INTERACTIVE MATPLOTLIB BACKENDS
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start


install:
    - conda create -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # ADD STSCI ASTROCONDA CHANNEL
    - conda config --add channels http://ssb.stsci.edu/astroconda

    # RTD deps
    - $PIP_INSTALL -r source/rtd-pip-requirements.txt


script:
   - python setup.py install
